
#NUMPY



### Escalar

Un **escalar** es una cantidad única que representa un solo valor. No tiene dirección, solo magnitud.

**Ejemplo:** La temperatura de una habitación (25°C), la edad de una persona (30 años), o la velocidad de la luz (299,792,458 m/s).

In [1]:
import numpy as np

# Un escalar en Python puede ser un número entero o flotante
velocidad_luz = 299792458  # Escalar
temperatura = 25.5       # Escalar

print(f"Velocidad de la luz (escalar): {velocidad_luz}")
print(f"Temperatura (escalar): {temperatura}")
print(f"Tipo de velocidad_luz: {type(velocidad_luz)}")

Velocidad de la luz (escalar): 299792458
Temperatura (escalar): 25.5
Tipo de velocidad_luz: <class 'int'>


### Vector

Un **vector** es una secuencia ordenada de escalares. Representa una cantidad que tiene magnitud y dirección. En una dimensión, es un arreglo de números.

**Ejemplo:** Las coordenadas de un punto en el espacio (x, y, z), o el conjunto de latencias de un microservicio en diferentes regiones.

In [ ]:
# Un vector en Python puede representarse con una lista o un array de NumPy
coordenadas = [3, 4, 5]  # Vector
latencias_gateway = np.array([100, 120, 90]) # Vector de latencias en ms para 3 regiones

print(f"Coordenadas (vector): {coordenadas}")
print(f"Latencias del Gateway (vector): {latencias_gateway}")
print(f"Tipo de latencias_gateway: {type(latencias_gateway)}")
print(f"Dimensión (shape) del vector: {latencias_gateway.shape}")


Coordenadas (vector): [3, 4, 5]
Latencias del Gateway (vector): [100 120  90]
Tipo de latencias_gateway: <class 'numpy.ndarray'>
Dimensión (shape) del vector: (3,)


### Matriz

Una **matriz** es un arreglo bidimensional de escalares, organizado en filas y columnas. Se puede ver como un conjunto de vectores dispuestos vertical u horizontalmente.

**Ejemplo:** Una tabla de datos donde las filas representan observaciones y las columnas representan diferentes características, o un conjunto de latencias de varios microservicios en distintas regiones.

In [ ]:
# Una matriz en Python se puede representar con una lista anidada o un array 2D de NumPy

# Latencias (ms) para 2 microservicios en 3 regiones
# Fila 1: Latencias de Auth (Región 1, Región 2, Región 3)
# Fila 2: Latencias de Billing (Región 1, Región 2, Región 3)
latencias_ms = np.array([
    [50, 60, 55],    # Auth
    [80, 75, 85]     # Billing
])

print(f"Matriz de latencias:\n{latencias_ms}")
print(f"Tipo de latencias_ms: {type(latencias_ms)}")
print(f"Dimensión (shape) de la matriz: {latencias_ms.shape}")

Matriz de latencias:
[[50 60 55]
 [80 75 85]]
Tipo de latencias_ms: <class 'numpy.ndarray'>
Dimensión (shape) de la matriz: (2, 3)


### Tensor

Un **tensor** es una generalización de escalares (tensor de orden 0), vectores (tensor de orden 1) y matrices (tensor de orden 2) a un número arbitrario de dimensiones (o 'ejes'). Los tensores son fundamentales en campos como el aprendizaje profundo.

**Ejemplo:** Una imagen a color puede ser representada como un tensor 3D (altura x anchura x canales de color), o las métricas de latencia de varios microservicios en diferentes regiones y en distintos períodos de tiempo.

In [ ]:
# Un tensor en Python se representa con un array de NumPy con más de 2 dimensiones

# Datos de latencia para 4 microservicios, 3 regiones y 2 períodos de tiempo (Hora Pico, Hora Valle)
# Dimensiones: (Microservicio, Región, Período de Tiempo)
latencias_completas = np.array([
    # Microservicio 1: Auth
    [
        [50, 70],  # Región 1 (Pico, Valle)
        [60, 80],  # Región 2 (Pico, Valle)
        [55, 75]   # Región 3 (Pico, Valle)
    ],
    # Microservicio 2: Billing
    [
        [80, 100], # Región 1 (Pico, Valle)
        [75, 95],  # Región 2 (Pico, Valle)
        [85, 105]  # Región 3 (Pico, Valle)
    ],
    # Microservicio 3: Inventory
    [
        [30, 45],  # Región 1 (Pico, Valle)
        [35, 50],  # Región 2 (Pico, Valle)
        [40, 55]   # Región 3 (Pico, Valle)
    ],
    # Microservicio 4: Gateway
    [
        [150, 200],# Región 1 (Pico, Valle)
        [160, 210],# Región 2 (Pico, Valle)
        [155, 205] # Región 3 (Pico, Valle)
    ]
])

print(f"Tensor de latencias:\n{latencias_completas}")
print(f"Tipo de latencias_completas: {type(latencias_completas)}")
print(f"Dimensión (shape) del tensor: {latencias_completas.shape}")
print(f"Número de dimensiones (orden/rango) del tensor: {latencias_completas.ndim}")

Tensor de latencias:
[[[ 50  70]
  [ 60  80]
  [ 55  75]]

 [[ 80 100]
  [ 75  95]
  [ 85 105]]

 [[ 30  45]
  [ 35  50]
  [ 40  55]]

 [[150 200]
  [160 210]
  [155 205]]]
Tipo de latencias_completas: <class 'numpy.ndarray'>
Dimensión (shape) del tensor: (4, 3, 2)
Número de dimensiones (orden/rango) del tensor: 3


### Normalización de Latencias

Vamos a normalizar las latencias aplicando un factor de 'Ruido de Red' (escalar) al tensor de `latencias_completas`. Esto simula un ajuste general debido a condiciones de red externas.

In [ ]:
# Definir el factor de Ruido de Red (Escalar)
factor_ruido_red = 1.15  # Un incremento del 15%

# Normalizar las latencias multiplicando el tensor por el escalar
# NumPy aplica automáticamente la multiplicación elemento a elemento (broadcasting)
latencias_normalizadas = latencias_completas * factor_ruido_red

print(f"Factor de Ruido de Red: {factor_ruido_red}")
print(f"\nLatencias Completas Originales:\n{latencias_completas}")
print(f"\nLatencias Normalizadas:\n{latencias_normalizadas}")
print(f"Dimensión del tensor normalizado: {latencias_normalizadas.shape}")

Factor de Ruido de Red: 1.15

Latencias Completas Originales:
[[[ 50  70]
  [ 60  80]
  [ 55  75]]

 [[ 80 100]
  [ 75  95]
  [ 85 105]]

 [[ 30  45]
  [ 35  50]
  [ 40  55]]

 [[150 200]
  [160 210]
  [155 205]]]

Latencias Normalizadas:
[[[ 57.5   80.5 ]
  [ 69.    92.  ]
  [ 63.25  86.25]]

 [[ 92.   115.  ]
  [ 86.25 109.25]
  [ 97.75 120.75]]

 [[ 34.5   51.75]
  [ 40.25  57.5 ]
  [ 46.    63.25]]

 [[172.5  230.  ]
  [184.   241.5 ]
  [178.25 235.75]]]
Dimensión del tensor normalizado: (4, 3, 2)


### Ponderación de Latencias por Microservicio

Ahora, aplicaremos un factor de importancia diferente a cada microservicio. Esto se logra multiplicando las latencias normalizadas por un vector de pesos, donde cada elemento del vector corresponde a un microservicio.

In [ ]:
# Definir el vector de pesos para cada microservicio
# Asumiendo el orden: Auth, Billing, Inventory, Gateway
# El Gateway tiene más impacto, por lo que le damos un peso mayor.
# El Billing tiene un impacto menor.
pesos_microservicio = np.array([1.0, 0.9, 1.0, 1.2]) # Vector de pesos

# Para aplicar el vector de pesos al tensor (4, 3, 2),
# necesitamos que el vector de pesos se 'alinee' con la primera dimensión (microservicios).
# NumPy puede manejar esto con broadcasting si el vector de pesos tiene la forma (4, 1, 1).
latencias_ponderadas = latencias_normalizadas * pesos_microservicio[:, np.newaxis, np.newaxis]

print(f"Vector de pesos por microservicio: {pesos_microservicio}")
print(f"\nLatencias Normalizadas:\n{latencias_normalizadas}")
print(f"\nLatencias Ponderadas:\n{latencias_ponderadas}")
print(f"Dimensión del tensor ponderado: {latencias_ponderadas.shape}")

Vector de pesos por microservicio: [1.  0.9 1.  1.2]

Latencias Normalizadas:
[[[ 57.5   80.5 ]
  [ 69.    92.  ]
  [ 63.25  86.25]]

 [[ 92.   115.  ]
  [ 86.25 109.25]
  [ 97.75 120.75]]

 [[ 34.5   51.75]
  [ 40.25  57.5 ]
  [ 46.    63.25]]

 [[172.5  230.  ]
  [184.   241.5 ]
  [178.25 235.75]]]

Latencias Ponderadas:
[[[ 57.5    80.5  ]
  [ 69.     92.   ]
  [ 63.25   86.25 ]]

 [[ 82.8   103.5  ]
  [ 77.625  98.325]
  [ 87.975 108.675]]

 [[ 34.5    51.75 ]
  [ 40.25   57.5  ]
  [ 46.     63.25 ]]

 [[207.    276.   ]
  [220.8   289.8  ]
  [213.9   282.9  ]]]
Dimensión del tensor ponderado: (4, 3, 2)


### Análisis del Tensor de Latencias Ponderadas

Finalmente, vamos a analizar el tensor de latencias ponderadas para extraer información útil. Esto puede incluir calcular promedios globales, promedios por microservicio, o identificar los valores máximos y mínimos.

In [ ]:
# Calcular la latencia promedio global de todos los microservicios, regiones y períodos de tiempo
latencia_promedio_global = np.mean(latencias_ponderadas)

# Calcular la latencia promedio por microservicio (promediando a través de regiones y períodos de tiempo)
# Axis 0 son los microservicios, entonces promediamos sobre axis 1 (regiones) y axis 2 (periodos de tiempo)
latencia_promedio_por_microservicio = np.mean(latencias_ponderadas, axis=(1, 2))

# Encontrar la latencia máxima y mínima en todo el tensor
latencia_maxima = np.max(latencias_ponderadas)
latencia_minima = np.min(latencias_ponderadas)

# Nombres de los microservicios para una mejor visualización
nombres_microservicios = ["Auth", "Billing", "Inventory", "Gateway"]

print(f"Tensor de Latencias Ponderadas:\n{latencias_ponderadas}")
print(f"\nLatencia Promedio Global: {latencia_promedio_global:.2f} ms")
print(f"\nLatencia Máxima Registrada: {latencia_maxima:.2f} ms")
print(f"Latencia Mínima Registrada: {latencia_minima:.2f} ms")

print("\nLatencia Promedio por Microservicio:")
for i, nombre in enumerate(nombres_microservicios):
    print(f"  {nombre}: {latencia_promedio_por_microservicio[i]:.2f} ms")

Tensor de Latencias Ponderadas:
[[[ 57.5    80.5  ]
  [ 69.     92.   ]
  [ 63.25   86.25 ]]

 [[ 82.8   103.5  ]
  [ 77.625  98.325]
  [ 87.975 108.675]]

 [[ 34.5    51.75 ]
  [ 40.25   57.5  ]
  [ 46.     63.25 ]]

 [[207.    276.   ]
  [220.8   289.8  ]
  [213.9   282.9  ]]]

Latencia Promedio Global: 116.29 ms

Latencia Máxima Registrada: 289.80 ms
Latencia Mínima Registrada: 34.50 ms

Latencia Promedio por Microservicio:
  Auth: 74.75 ms
  Billing: 93.15 ms
  Inventory: 48.88 ms
  Gateway: 248.40 ms


#ejemplo

1. Narrativa del Problema
Trabajas en el equipo de Site Reliability Engineering (SRE) de una plataforma SaaS. El sistema consta de 4 microservicios críticos (Auth, Billing, Inventory, Gateway).

Para optimizar la infraestructura, has recolectado métricas de Latencia (ms) en 3 regiones geográficas diferentes. Además, los datos se han capturado en 2 periodos de tiempo (Hora Pico y Hora Valle).

Necesitas procesar estos datos para:

Normalizar: Ajustar las latencias según un factor de "Ruido de Red" constante (Escalar).

Ponderar: Aplicar un factor de importancia a cada microservicio, ya que el Gateway impacta más que el Billing (Vector).


In [ ]:
import numpy as np

# --- DEFINICIÓN DE ESTRUCTURAS DE DATOS ---

# 1. ESCALAR: Retraso base de la red (overhead de fibra óptica)
retraso_base = 1.2  # ms

# 2. VECTOR: Factores de peso por Microservicio (Auth, Billing, Inventory, Gateway)
# Dimensiones: (4,)
pesos_servicios = np.array([1.0, 0.8, 1.1, 2.5])

# 3. MATRIZ: Latencias medidas en 3 Regiones (filas) para los 4 Servicios (columnas)
# Dimensiones: (3, 4)
latencias_regionales = np.array([
    [45.2, 80.1, 55.3, 20.5],  # US-East
    [120.5, 150.2, 110.8, 45.1], # EU-West
    [200.1, 210.5, 190.2, 90.4]  # AP-South
])

# 4. TENSOR: Datos capturados en 2 estados (Hora Valle, Hora Pico)
# Dimensiones: (2, 3, 4)
# Simulamos que en Hora Pico (índice 1) las latencias suben un 50%
metricas_sistema = np.array([
    latencias_regionales,          # Hora Valle
    latencias_regionales * 1.5     # Hora Pico
])

print(f"Estructura del Tensor de Métricas: {metricas_sistema.shape}")

Estructura del Tensor de Métricas: (2, 3, 4)


Aplicación de Operaciones y Broadcasting
Como ingeniero, debes evitar los bucles for para que el sistema de monitoreo sea escalable. Usaremos Broadcasting para procesar todo el bloque de datos simultáneamente.

In [ ]:
# --- PROCESAMIENTO VECTORIZADO ---

# Paso A: Eliminar el ruido base (Escalar -> Tensor)
# Paso B: Aplicar la importancia de negocio (Vector -> Tensor)
# El vector (4,) se alineará automáticamente con la última dimensión del tensor (2, 3, 4)

metricas_ajustadas = (metricas_sistema - retraso_base) * pesos_servicios

# Visualización de resultados para "Hora Pico" en "US-East"
print("Latencias originales (Hora Pico - US-East):")
print(metricas_sistema[1, 0, :])

print("\nLatencias ponderadas y corregidas (Hora Pico - US-East):")
print(np.round(metricas_ajustadas[1, 0, :], 2))

Latencias originales (Hora Pico - US-East):
[ 67.8  120.15  82.95  30.75]

Latencias ponderadas y corregidas (Hora Pico - US-East):
[66.6  95.16 89.92 73.88]


Supongamos que ahora el equipo de infraestructura te da un vector con el Costo de Servidor por cada una de las 3 regiones: costos = [0.05, 0.07, 0.04].

Si quieres multiplicar tu matriz latencias_regionales (3, 4) por estos costos para obtener un "Índice de Costo por Latencia":

¿Qué forma (shape) debería tener el vector de costos para que el broadcasting funcione correctamente?

Pista: El vector original es (3,). Para que NumPy lo "estire" a través de las 4 columnas de servicios, debe tener la forma (3, 1).

In [ ]:
costos = np.array([0.05, 0.07, 0.04]).reshape(3, 1)
indice_impacto = latencias_regionales * costos
print("\nMatriz de Impacto por Región:\n", indice_impacto)


Matriz de Impacto por Región:
 [[ 2.26   4.005  2.765  1.025]
 [ 8.435 10.514  7.756  3.157]
 [ 8.004  8.42   7.608  3.616]]
